apiVersion: v1
entries:
  appstore-metadata-service:
  - apiVersion: v1
    appVersion: 0.1.11
    created: "2023-08-31T17:18:47.418207783Z"
    description: Appstore Metadata Service
    digest: 2fc7299234760a578ef5e28cb120d34d06de4f3c295ebeefed9b24de837b9aed
    home: https://github.com/LibertyGlobal/appstore-metadata-service
    kubeVersion: '>=1.12.0-0'
    name: appstore-metadata-service
    sources:
    - https://github.com/LibertyGlobal/appstore-metadata-service
    urls:
    - https://libertyglobal.github.io/appstore-metadata-service/charts/appstore-metadata-service-0.1.11.tgz
    version: 0.1.11
  - apiVersion: v1
    appVersion: 0.1.10
    created: "2023-08-31T17:18:47.417766882Z"
    description: Appstore Metadata Service
    digest: 1c566e358fd453dc67328193da933aa263bc025b7f40ca578cabd422177944fe
    home: https://github.com/LibertyGlobal/appstore-metadata-service
    kubeVersion: '>=1.12.0-0'
    name: appstore-metadata-service
    sources:
    - https://github.com/LibertyGlobal/appstore-metadata-service
    urls:
    - https://libertyglobal.github.io/appstore-metadata-service/charts/appstore-metadata-service-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v1
    appVersion: 0.1.9
    created: "2023-08-31T17:18:47.419823287Z"
    description: Appstore Metadata Service
    digest: 39232af0761002469952ea4df6bbf9d527cb4307c18d5427286a253de1da8787
    home: https://github.com/LibertyGlobal/appstore-metadata-service
    kubeVersion: '>=1.12.0-0'
    name: appstore-metadata-service
    sources:
    - https://github.com/LibertyGlobal/appstore-metadata-service
    urls:
    - https://libertyglobal.github.io/appstore-metadata-service/charts/appstore-metadata-service-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v1
    appVersion: 0.1.8
    created: "2023-08-31T17:18:47.419059985Z"
    description: Appstore Metadata Service
    digest: 74c0f331b43d0980f6a049aedd0c63c71db0f5427a08873f8164ec1ee2d5c8b6
    home: https://github.com/LibertyGlobal/appstore-metadata-service
    kubeVersion: '>=1.12.0-0'
    name: appstore-metadata-service
    sources:
    - https://github.com/LibertyGlobal/appstore-metadata-service
    urls:
    - https://libertyglobal.github.io/appstore-metadata-service/charts/appstore-metadata-service-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v1
    appVersion: 0.1.7
    created: "2023-08-31T17:18:47.418633584Z"
    description: Appstore Metadata Service
    digest: 59c8547ffda37b62928e375b1e792a58a6f34022c1bb591d380041a5d4aefccf
    home: https://github.com/LibertyGlobal/appstore-metadata-service
    kubeVersion: '>=1.12.0-0'
    name: appstore-metadata-service
    sources:
    - https://github.com/LibertyGlobal/appstore-metadata-service
    urls:
    - https://libertyglobal.github.io/appstore-metadata-service/charts/appstore-metadata-service-0.1.7.tgz
    version: 0.1.7
generated: "2023-08-31T17:18:47.41713358Z"
