#
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2022 Liberty Global Technology Services BV
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM postgres:12

# ENV POSTGRES_HOST_AUTH_METHOD trust
# ENV POSTGRES_USER asms
# ENV POSTGRES_PASSWORD asms
# ENV POSTGRES_DB asms

# USER postgres
# RUN ls  "$PGDATA" 
# RUN  pg_ctl -w -D "$PGDATA" start 
# RUN createuser -l -r asms && \
#     createdb -O asms --encoding=utf8 --lc-collate="en_US.utf8"  --lc-ctype="en_US.utf8" asms && \
#     postgres asms -x -c "alter user asms with password '123qwe'"