#
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2023 Liberty Global Technology Services BV
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Release helm package
on:
  workflow_call:
    inputs:
      version:
        description: "Helm package version"
        default: true
        type: string
    secrets:
      token:
        required: true
env:
  CI_COMMIT_AUTHOR: Dac-Cloud-Bot
  CI_COMMIT_AUTHOR_EMAIL: dac-cloud@libertyglobal.com
  CI_COMMIT_MESSAGE: "[CI] Add Helm Chart"
  HELM_REPOSITORY: https://libertyglobal.github.io/appstore-metadata-service/charts
jobs:
  release-helm:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name ${{ env.CI_COMMIT_AUTHOR }}
          git config user.email ${{ env.CI_COMMIT_AUTHOR_EMAIL }}
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.5.0
      - name: Generate and Publish Helm
        run: |
          git pull
          cat charts/index.yaml | grep '#' > charts/license.txt
          helm package --version ${{ inputs.version }} --app-version ${{ inputs.version }} helm/appstore-metadata-service -d charts/
          helm repo index charts/ --url ${{ env.HELM_REPOSITORY }}
          { cat charts/license.txt; cat charts/index.yaml; } > charts/index.yaml.withlicenseheader
          mv charts/index.yaml.withlicenseheader charts/index.yaml
          rm charts/license.txt
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "{{ env.CI_COMMIT_AUTHOR_EMAIL }}"
          git add charts/
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push

